server:
  port: 8080

# Database Configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/taskflow
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration (MATCHES JwtUtil.java)
jwt:
  secret: "c2VjcmV0c3VwZXJzZWN1cmVrZXltdXN0YmU2NGVuY29kZWQ="
  expiration: 86400 # 24 hours in SECONDS (86400000 ms / 1000 ms/s = 86400 s)